<?php

namespace Database\Seeders;

use App\Models\Destination;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $destinations = [
    [
        'name' => 'Paris',
        'description' => 'The capital city of France, known for its art, fashion, and culture.',
        'country' => 'France',
        'city' => 'Paris',
        'visa' => 'Required for some countries',
        'language' => 'French',
        'currency' => 'Euro',
        'activity' => 'Eiffel Tower, Louvre Museum, Seine River Cruise',
        'visit_time' => 'April to June, September to November',
        'safety' => 'Generally safe, beware of pickpockets',
        'area' => '105.4 km²',
        'time_zone' => 'CET (UTC+1)',
        'featured_photo' => 'paris.jpg',
        'view_count' => 12000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'New York City',
        'description' => 'A bustling metropolis known for its skyscrapers and Times Square.',
        'country' => 'USA',
        'city' => 'New York',
        'visa' => 'ESTA for visa waiver countries',
        'language' => 'English',
        'currency' => 'US Dollar',
        'activity' => 'Statue of Liberty, Central Park, Broadway Shows',
        'visit_time' => 'April to June, September to November',
        'safety' => 'Safe, but avoid certain neighborhoods at night',
        'area' => '783.8 km²',
        'time_zone' => 'EST (UTC-5)',
        'featured_photo' => 'nyc.jpg',
        'view_count' => 25000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Tokyo',
        'description' => 'The capital of Japan, known for its mix of modern and traditional culture.',
        'country' => 'Japan',
        'city' => 'Tokyo',
        'visa' => 'Visa-free for many countries',
        'language' => 'Japanese',
        'currency' => 'Japanese Yen',
        'activity' => 'Shibuya Crossing, Tokyo Tower, Akihabara',
        'visit_time' => 'March to May, September to November',
        'safety' => 'One of the safest cities in the world',
        'area' => '2,194 km²',
        'time_zone' => 'JST (UTC+9)',
        'featured_photo' => 'tokyo.jpg',
        'view_count' => 18000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Dubai',
        'description' => 'A futuristic city in the UAE known for luxury shopping and skyscrapers.',
        'country' => 'UAE',
        'city' => 'Dubai',
        'visa' => 'Visa on arrival for many countries',
        'language' => 'Arabic, English widely spoken',
        'currency' => 'UAE Dirham',
        'activity' => 'Burj Khalifa, Desert Safari, Dubai Mall',
        'visit_time' => 'November to March',
        'safety' => 'Very safe, strict laws',
        'area' => '4,114 km²',
        'time_zone' => 'GST (UTC+4)',
        'featured_photo' => 'dubai.jpg',
        'view_count' => 15000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Sydney',
        'description' => 'A vibrant Australian city famous for its harbor and beaches.',
        'country' => 'Australia',
        'city' => 'Sydney',
        'visa' => 'ETA for most countries',
        'language' => 'English',
        'currency' => 'Australian Dollar',
        'activity' => 'Sydney Opera House, Bondi Beach, Blue Mountains',
        'visit_time' => 'September to November, March to May',
        'safety' => 'Safe, but be cautious of wildlife',
        'area' => '12,368 km²',
        'time_zone' => 'AEST (UTC+10)',
        'featured_photo' => 'sydney.jpg',
        'view_count' => 11000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'London',
        'description' => 'The capital of the UK, known for its history and landmarks.',
        'country' => 'United Kingdom',
        'city' => 'London',
        'visa' => 'Required for some countries',
        'language' => 'English',
        'currency' => 'British Pound',
        'activity' => 'Big Ben, Buckingham Palace, London Eye',
        'visit_time' => 'May to September',
        'safety' => 'Safe, but avoid some areas at night',
        'area' => '1,572 km²',
        'time_zone' => 'GMT (UTC+0)',
        'featured_photo' => 'london.jpg',
        'view_count' => 20000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Rome',
        'description' => 'The capital of Italy, known for ancient history and Vatican City.',
        'country' => 'Italy',
        'city' => 'Rome',
        'visa' => 'Schengen Visa required for many countries',
        'language' => 'Italian',
        'currency' => 'Euro',
        'activity' => 'Colosseum, Vatican Museums, Trevi Fountain',
        'visit_time' => 'April to June, September to October',
        'safety' => 'Safe, but beware of scams',
        'area' => '1,285 km²',
        'time_zone' => 'CET (UTC+1)',
        'featured_photo' => 'rome.jpg',
        'view_count' => 13000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Bangkok',
        'description' => 'The capital of Thailand, famous for temples and street food.',
        'country' => 'Thailand',
        'city' => 'Bangkok',
        'visa' => 'Visa-free for many countries',
        'language' => 'Thai',
        'currency' => 'Thai Baht',
        'activity' => 'Grand Palace, Floating Markets, Khao San Road',
        'visit_time' => 'November to February',
        'safety' => 'Safe, but avoid tourist scams',
        'area' => '1,569 km²',
        'time_zone' => 'ICT (UTC+7)',
        'featured_photo' => 'bangkok.jpg',
        'view_count' => 9000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Istanbul',
        'description' => 'A historic city that connects Europe and Asia.',
        'country' => 'Turkey',
        'city' => 'Istanbul',
        'visa' => 'E-Visa for many countries',
        'language' => 'Turkish',
        'currency' => 'Turkish Lira',
        'activity' => 'Hagia Sophia, Bosphorus Cruise, Grand Bazaar',
        'visit_time' => 'April to June, September to October',
        'safety' => 'Safe, but avoid political protests',
        'area' => '5,343 km²',
        'time_zone' => 'TRT (UTC+3)',
        'featured_photo' => 'istanbul.jpg',
        'view_count' => 14000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Rio de Janeiro',
        'description' => 'A Brazilian city known for its beaches and Carnival festival.',
        'country' => 'Brazil',
        'city' => 'Rio de Janeiro',
        'visa' => 'Visa required for some countries',
        'language' => 'Portuguese',
        'currency' => 'Brazilian Real',
        'activity' => 'Christ the Redeemer, Copacabana Beach, Sugarloaf Mountain',
        'visit_time' => 'December to March',
        'safety' => 'Caution required in certain areas',
        'area' => '1,221 km²',
        'time_zone' => 'BRT (UTC-3)',
        'featured_photo' => 'rio.jpg',
        'view_count' => 8000,
        'created_at' => now(),
        'updated_at' => now(),
    ],
];


        foreach ($destinations as $destination) {
            Destination::create($destination);
        }

    }
}
